version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: product_order_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: tutorial
      MYSQL_USER: lukas
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p rootpwd"]
      timeout: 20s
      retries: 3

volumes:
  mysql_data:
